on:
  pull_request:
    paths-ignore:
      - 'README.rst'

jobs:
  preview:
    name: Preview updates to stack resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pulumi/actions@v1
        with:
          command: preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_ROOT: infra
          PULUMI_BACKEND_URL: s3://pulumi.linhart.tech
          IS_PR_WORKFLOW: true
          COMMENT_ON_PR: 1
